name: HCPCS Pipeline Manual

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          pip install -r hcpcs-pipeline/requirements.txt

      - name: Run Scraper
        run: |
          cd hcpcs-pipeline/scraper
          python scrape_hcpcs.py

      - name: Run Loader
        run: |
          cd hcpcs-pipeline/loader
          python load_to_sqlite.py

      - name: Run Validator
        run: |
          cd hcpcs-pipeline/validation
          python validate.py

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: hcpcs-data
          path: |
            hcpcs-pipeline/hcpcs.db
            hcpcs-pipeline/scaper_output/hcpcs_data_full.json
