name: HCPCS Pipeline

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: |
          cd scraper
          python scrape_hcpcs.py

      - name: Run Loader
        run: |
          cd loader
          python load_to_sqlite.py

      - name: Run Validator
        run: |
          cd validator
          python validate.py

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: hcpcs-data
          path: |
            hcpcs.db
            scraper_output/hcpcs_data_full.json
